#!/usr/bin/env python3
"""
Recompute the project statistics table in the root README.md.

Reads real artifacts:
  - outputs/astronaut_data_mapping_v1_0/integrated_evidence_graph_stats_v1_0.json
    (falls back to integrated_evidence_graph_v1_0.json) for node/edge/type counts.
  - sources_pdf/*.pdf for the PDF source count.
  - every *.json under the project (excluding .git/ and dist/) for the JSON file count.

Replaces ONLY the content between:
  <!-- AUTO-GENERATED-STATS:START -->
  <!-- AUTO-GENERATED-STATS:END -->

Validation status is determined by running scripts/run_all_validations.py (use
--no-validate to skip and mark the status as "not evaluated").

If expected output files are missing, the script FAILS (non-zero exit) and does NOT
write fabricated numbers.
"""

from __future__ import annotations

import argparse
import json
import logging
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _project_paths import PROJECT_ROOT, OUTPUTS_DIR, SOURCES_PDF_DIR, SCRIPTS_DIR  # noqa: E402

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger("update_readme_stats")

README = PROJECT_ROOT / "README.md"
PKG_DIR = OUTPUTS_DIR / "astronaut_data_mapping_v1_0"
STATS_FILE = PKG_DIR / "integrated_evidence_graph_stats_v1_0.json"
GRAPH_FILE = PKG_DIR / "integrated_evidence_graph_v1_0.json"

START_MARKER = "<!-- AUTO-GENERATED-STATS:START -->"
END_MARKER = "<!-- AUTO-GENERATED-STATS:END -->"


def load_graph_stats() -> dict[str, Any]:
    if STATS_FILE.is_file():
        stats = json.loads(STATS_FILE.read_text(encoding="utf-8")).get("stats", {})
        if stats.get("node_count") is not None:
            logger.info("Loaded stats from %s", STATS_FILE.name)
            return stats
    if GRAPH_FILE.is_file():
        logger.info("Stats file unusable; computing from %s", GRAPH_FILE.name)
        graph = json.loads(GRAPH_FILE.read_text(encoding="utf-8"))
        nodes, edges = graph.get("nodes", []), graph.get("edges", [])
        by_type: dict[str, int] = {}
        for n in nodes:
            by_type[n.get("type")] = by_type.get(n.get("type"), 0) + 1
        return {"node_count": len(nodes), "edge_count": len(edges),
                "nodes_by_type": by_type}
    raise FileNotFoundError(
        f"Required output missing: neither {STATS_FILE} nor {GRAPH_FILE} exists. "
        "Cannot compute statistics; refusing to write fake numbers."
    )


def count_pdfs() -> int:
    if not SOURCES_PDF_DIR.is_dir():
        raise FileNotFoundError(f"Required directory missing: {SOURCES_PDF_DIR}")
    return len(list(SOURCES_PDF_DIR.glob("*.pdf")))


def count_json_files() -> int:
    return sum(
        1
        for p in PROJECT_ROOT.rglob("*.json")
        if ".git" not in p.parts and "dist" not in p.parts
    )


def evaluate_validation_status(run_validations: bool) -> str:
    if not run_validations:
        return "Not evaluated (run `scripts/run_all_validations.py`)"
    runner = SCRIPTS_DIR / "run_all_validations.py"
    if not runner.is_file():
        return "Unknown (run_all_validations.py not found)"
    logger.info("Running run_all_validations.py to determine validation status...")
    proc = subprocess.run(
        [sys.executable, str(runner)],
        cwd=str(PROJECT_ROOT),
        capture_output=True,
        text=True,
    )
    return "PASS" if proc.returncode == 0 else "FAIL"


def build_stats_block(stats: dict[str, Any], pdfs: int, json_files: int,
                      validation_status: str) -> str:
    by_type = stats.get("nodes_by_type", {})
    rows = [
        ("Total nodes", stats.get("node_count")),
        ("Total edges", stats.get("edge_count")),
        ("Measured parameters", by_type.get("measured_parameter")),
        ("Required measurements", by_type.get("required_measurement")),
        ("Hidden-state nodes", by_type.get("hidden_state")),
        ("Guardrails", by_type.get("guardrail")),
        ("PDF sources", pdfs),
        ("JSON files", json_files),
        ("Validation status", validation_status),
    ]
    missing = [name for name, value in rows if value is None]
    if missing:
        raise ValueError(f"Missing required statistic(s): {missing}")

    lines = [
        f"_Last updated: {datetime.now(timezone.utc).isoformat()} "
        f"(generated by `scripts/update_readme_stats.py`)._",
        "",
        "| Metric | Value |",
        "|---|---|",
    ]
    for name, value in rows:
        lines.append(f"| {name} | {value} |")
    return "\n".join(lines)


def replace_between_markers(text: str, block: str) -> str:
    if START_MARKER not in text or END_MARKER not in text:
        raise ValueError(
            f"README.md is missing the AUTO-GENERATED-STATS markers "
            f"({START_MARKER} / {END_MARKER})."
        )
    start = text.index(START_MARKER) + len(START_MARKER)
    end = text.index(END_MARKER)
    return text[:start] + "\n" + block + "\n" + text[end:]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--no-validate",
        action="store_true",
        help="Do not run validators to determine status; mark as not evaluated.",
    )
    args = parser.parse_args()

    if not README.is_file():
        logger.error("README.md not found at %s", README)
        return 1

    try:
        stats = load_graph_stats()
        pdfs = count_pdfs()
        json_files = count_json_files()
        validation_status = evaluate_validation_status(not args.no_validate)
        block = build_stats_block(stats, pdfs, json_files, validation_status)
    except (FileNotFoundError, ValueError) as exc:
        logger.error("FAILED to compute statistics: %s", exc)
        return 1

    text = README.read_text(encoding="utf-8")
    try:
        updated = replace_between_markers(text, block)
    except ValueError as exc:
        logger.error(str(exc))
        return 1

    README.write_text(updated, encoding="utf-8")
    logger.info("Updated statistics block in %s", README.name)
    print("\n" + block)
    return 0


if __name__ == "__main__":
    sys.exit(main())
